config/routes.rb
Rails.application.routes.draw do

	root 'pages#home';
	
  get '/home' => 'pages#home'

  #get '/recipes' => 'recipes#index'
  #get '/recipes/new' => 'recipes#new', as: 'new_recipe'
  #post '/recipes' => 'recipes#create'
  #get '/recipes/:id/edit' => 'recipes#edit', as: 'edit_recipe'
  #patch '/recipes/:id' => 'recipes#update'
  #put '/recipes/:id' => 'recipes#update'
  #get '/recipes/:id' => 'recipes#show', as: 'recipe'
  #delete '/recipes/:id' => 'recipes#destroy'

  #the following creates all the above by default
  resources :recipes do
    member do
      post 'like'
    end
  end


  resources :chefs, except: [:new, :destroy]

  get '/register' => 'chefs#new'

  get 'login' => 'logins#new'
  post 'login' => 'logins#create'
  get 'logout' => 'logins#destroy'

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]

end

app/models/chef.rb
class Chef < ActiveRecord::Base
	has_many :recipes
	has_many :likes
	
	before_save { self.email = email.downcase }
	validates :chefname, presence: true, length: { minimum: 3, maximum: 40 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105 },
										uniqueness: { case_sensitive: false },
										format: { with: VALID_EMAIL_REGEX }

	has_secure_password
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
	before_action :set_chef, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update]

	def index
		@chefs = Chef.paginate(page: params[:page], per_page: 5)
	end

	def new
		@chef = Chef.new
	end

	def create
		@chef = Chef.new(chef_params)

		if(@chef.save)
			flash[:success] = "Congratulations on creating your account chef #{@chef.chefname}!"
			session[:chef_id] = @chef.id
			redirect_to chef_path(@chef)
		else
			render :new
		end

	end

	def edit
	end

	def update
		if @chef.update(chef_params)
			flash[:success] = "Your profile has been updated successfully."
			redirect_to chef_path(@chef)
		else
			render :edit
		end
	end

	def show
		@recipes = @chef.recipes.paginate(page: params[:page], per_page: 5)
	end

	private

		def chef_params
			params.require(:chef).permit(:chefname, :email, :password)
		end

		def set_chef
			@chef = Chef.find(params[:id])
		end

		def require_same_user
			if current_user != @chef
				flash[:danger] = "You can only edit your own profile."
				redirect_to root_path
			end
		end

end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for @chef do |f| %>
			<%= f.label :chefname %>
			<%= f.text_field :chefname %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.submit(@chef.new_record? ? "Create Your Account!" : 'Update Your Profile', class: 'btn btn-success') %>
		<% end %>
	</div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit your account" %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "All Chefs" %>

<ul class="nav nav-tabs">
	<li>
		<%= link_to "Recipes", recipes_path %>
	</li>
	<li class="active">
		<%= link_to "Chefs", chefs_path %>
	</li>
</ul>

<div class="row">
	<div class="mol-md-4 col-md-4-offset center">
		<%= will_paginate %>
	</div>
</div>

<% @chefs.each do |chef| %>
	<div class="row">
		<div class="mol-md-4 col-md-4-offset center">
			<%= link_to gravatar_for(chef, size: 200), chef_path(chef) %>
			<p>
				<h5>Chef name: <%= link_to chef.chefname, chef_path(chef) %></h5>
			</p>
		</div>
	</div>
	<hr/>
<% end %>

<div class="row">
	<div class="mol-md-4 col-md-4-offset center">
		<%= will_paginate %>
	</div>
</div>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Register your account" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef: #{@chef.chefname}" %>

<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @chef, size: 200 %>
		<hr/>
	</div>
</div>

<div class="row">
	<div class="mol-md-4 col-md-4-offset center">
		<h3><em>Recipes:</em></h3>
		<%=will_paginate @recipes %>
	</div>
</div>

<% @recipes.each do |recipe| %>
	<div class="row">
		<div class="col-lg-6 well col-lg-offset-3">
			<h4><%= link_to recipe.name, recipe_path(recipe.id) %></h4>
			<p><%= recipe.summary %></p>
			<p>
				<span class='quiet'><small>Updated: <%= time_ago_in_words(recipe.updated_at) %></small></span>,
				<span class='quiet'><small>Created: <%= time_ago_in_words(recipe.created_at) %></small></span>
			</p>
			<div class="pull-right">
				<%= link_to like_recipe_path(recipe, like: true), method: :post do %>
					<i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
				<% end %>
				&nbsp &nbsp &nbsp &nbsp
				<%= link_to like_recipe_path(recipe, like: false), method: :post do %>
					<i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

<div class="row">
	<div class="mol-md-4 col-md-4-offset center">
		<%=will_paginate @recipes %>
	</div>
</div>